### ISSUE TITLE
Wrong re rule

### ISSUE THREAD

**Issue by AdrianWeaver** [Nuno-Jesus/Make-A-Make#5]
Your use of the re rule is incorrect.

`re: fclean all`

This rule will result in errors in case you use multi-jobs (option -j) of make.

You will actually try to build and clean at the same time which is weird.

I suggest writing it like so
`re:    fclean`
 `       make all`
 
 
 edit: watch bellow comment for the use of `$(MAKE)` that is better than `make`

**Comment by mjy9088** [comment]
instead of `make all`, `$(MAKE) all` is better.

especially if make is bmake and GNU Make is gmake

**Comment by Nuno-Jesus** [comment]
Got it, will fix it! About the MAKE variable, I believe I wrote it somewhere around the missing topics and forgot to add it here 😅
