### ISSUE TITLE
Vague explanation on variable declaration

### ISSUE THREAD

**Issue by AdrianWeaver** [Nuno-Jesus/Make-A-Make#6]
![image](https://github.com/Nuno-Jesus/Make-A-Make/assets/88249907/69b00dd3-8dd7-4299-a6f0-63e030f7a88a)

In here I would highly suggest replacing `:=`  by a simple `=`  it helps beginners understand that `=` is for a variable declaration

while `:`  is for a rule.

The subtle difference in the operators of variable assignment looks like it is beyond the scope of your simple make-a-make project.

Though it's true that `:=` is the correct syntax for a simple assignment, in practice `=`  really is fine to use as long as you do not set your variable with a script based on time or whatever else.

`:=` assigns a value to the variable that will be definitive for the whole make process
`=` calls the expression on the right hand sign of the operator resulting in possibly changing values (if a script is called)
`+=` will append
`?=` will assign a value only if the variable is unset before

**Comment by AdrianWeaver** [comment]
Maybe you could also add a suggestion to try and launch the makefile using `make -p >logs` then read the logs file.

This prevents a lot of errors especially when cpp projects come by and people keep using `CC`  `CFLAGS` and all.

**Comment by Nuno-Jesus** [comment]
I will review on the first comment. About the second one, I'm introducing flags later in a separate section when the new update comes into play. I'll look into it!
