### ISSUE TITLE
Changes done to .h/.hpp files

### ISSUE THREAD

**Issue by AdrianWeaver** [Nuno-Jesus/Make-A-Make#7]
As this page is intended to help students from the 42Network, I would suggest adding a paragraph on header files as dependencies.

Let's say you change the value of a `#define` instruction in one of your header files.
Now you are stuck with your project not compiling because you never explicitly said in your makefile that such file should be checked
to (re)compile.

A naive approach would be to add your .h file(s) as a variable then add such variable as dependency to your compilation rules.

A better approach would be to have a look at the flag `-MMD` and the (`-`)`include` instruction in make.

Good job so far !

**Comment by Nuno-Jesus** [comment]
Interesting 🤔 I see I have a lot of work to do, and I have to look further into that cause I really didn't know about it 😅 Thanks!
